const {
  withProjectBuildGradle,
  withAppBuildGradle,
  withAndroidManifest,
  withDangerousMod,
  createRunOncePlugin,
} = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/**
 * Carries the hand-tuned native build settings from the old checked-in
 * android/ folder over to the prebuild (CNG) workflow, where android/ is
 * regenerated on every `expo prebuild` and cannot be edited by hand.
 *
 * Anything expo-build-properties already covers (SDK levels, Kotlin version,
 * cleartext traffic, useLegacyPackaging, extra maven repos) is configured in
 * app.config.js instead — this plugin only handles what it cannot express.
 */

const NDK_VERSION = '27.1.12297006';

// react-native-geolocation-service@5.3.1 was compiled against
// play-services-location 21.0.1, where FusedLocationProviderClient was a class.
// 21.1.0+ made it an interface, which throws "Found interface ... but class was
// expected" at runtime. androidx.core 1.17.0+ likewise requires AGP 8.9.1 /
// compileSdk 36, ahead of what SDK 52 ships.
const DEPENDENCY_FORCES = [
  "force 'androidx.core:core-ktx:1.15.0'",
  "force 'androidx.core:core:1.15.0'",
  "force 'com.google.android.gms:play-services-location:21.0.1'",
];

/** Insert `addition` immediately after the first line matching `anchor`. */
function insertAfter(contents, anchor, addition, marker) {
  if (contents.includes(marker)) {
    return contents;
  }
  const match = contents.match(anchor);
  if (!match) {
    throw new Error(
      `withAllimNativeBuild: could not find anchor ${anchor} in the generated ` +
        'Gradle file. The Expo template likely changed — update this plugin.',
    );
  }
  const at = match.index + match[0].length;
  return contents.slice(0, at) + '\n' + addition + contents.slice(at);
}

/**
 * Root build.gradle: pin the NDK (27.x emits 16 KB-aligned ELF segments by
 * default) and apply the dependency forces above.
 */
const withRootGradle = config =>
  withProjectBuildGradle(config, cfg => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        'withAllimNativeBuild: only groovy build.gradle is supported.',
      );
    }
    let contents = cfg.modResults.contents;

    // The Expo template already declares ndkVersion — override it in place.
    if (/ndkVersion\s*=\s*["'][^"']+["']/.test(contents)) {
      contents = contents.replace(
        /ndkVersion\s*=\s*["'][^"']+["']/,
        `ndkVersion = "${NDK_VERSION}"`,
      );
    } else {
      contents = insertAfter(
        contents,
        /buildscript\s*\{\s*ext\s*\{/,
        `        ndkVersion = "${NDK_VERSION}"`,
        NDK_VERSION,
      );
    }

    // A second allprojects block is legal — Gradle merges them — so append
    // rather than rewriting the template's own block.
    if (!contents.includes('// allim:dependency-forces')) {
      contents += `
// allim:dependency-forces
allprojects {
    repositories {
        // Notifee ships its Android artifacts as a local maven repo inside
        // node_modules rather than publishing to a remote repository. The
        // path is anchored to $rootDir (= android/) so it resolves the same
        // way for every subproject, including :app.
        maven { url("\$rootDir/../node_modules/@notifee/react-native/android/libs") }
    }
    configurations.all {
        resolutionStrategy {
            ${DEPENDENCY_FORCES.join('\n            ')}
        }
    }
}
`;
    }

    cfg.modResults.contents = contents;
    return cfg;
  });

/**
 * app/build.gradle: the CMake stub build (see withCMakeStubs) plus the Kotlin
 * metadata-check opt-out that RN 0.76 + Firebase's Kotlin 2.x artifacts need.
 */
const withAppGradle = config =>
  withAppBuildGradle(config, cfg => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        'withAllimNativeBuild: only groovy build.gradle is supported.',
      );
    }
    let contents = cfg.modResults.contents;

    contents = insertAfter(
      contents,
      /android\s*\{/,
      `    // allim:kotlin-opts
    kotlinOptions {
        freeCompilerArgs += ["-Xskip-metadata-version-check"]
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
            version "3.22.1"
        }
    }`,
      '// allim:kotlin-opts',
    );

    contents = insertAfter(
      contents,
      /defaultConfig\s*\{/,
      `        // allim:abi-filters
        externalNativeBuild {
            cmake {
                abiFilters "arm64-v8a", "armeabi-v7a", "x86", "x86_64"
            }
        }`,
      '// allim:abi-filters',
    );

    cfg.modResults.contents = contents;
    return cfg;
  });

const CMAKE_LISTS = `cmake_minimum_required(VERSION 3.22.1)
project(allimandroid)

# Generated by plugins/withAllimNativeBuild.js — do not edit by hand.

# Align ELF LOAD segments to 16 KB so the app is compatible with Android 15+
# devices that use 16 KB page sizes (Pixel 8+, future devices). Without this
# the runtime falls back to "page size compatible mode" and logs a warning.
add_link_options("-Wl,-z,max-page-size=16384")

# In RN 0.76.x several libraries were merged into libreactnative.so but their
# Java/Kotlin callers still invoke SoLoader.loadLibrary() by the old names,
# which falls back to System.loadLibrary() -> dlopen -> "library not found".
# These stubs satisfy the dlopen check; actual symbols come from libreactnative.so.

function(add_stub name)
    add_library(\${name} SHARED src/main/cpp/stub.cpp)
    target_link_libraries(\${name} android log)
endfunction()

add_stub(hermes_executor)
add_stub(react_devsupportjni)
add_stub(reactnativejni)
add_stub(react_nativemodule_core)
`;

const STUB_CPP = `#include <jni.h>

// Generated by plugins/withAllimNativeBuild.js — do not edit by hand.
//
// Stub for libraries merged into libreactnative.so in React Native 0.76.x.
// SoLoader falls back to System.loadLibrary() which requires the .so file to
// exist on disk. These stubs satisfy that requirement; actual JNI symbols are
// registered by libreactnative.so's JNI_OnLoad.
JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved) {
    return JNI_VERSION_1_6;
}
`;

/**
 * Writes the CMake sources that app/build.gradle points at. prebuild wipes
 * android/, so these have to be re-emitted rather than committed.
 */
const withCMakeStubs = config =>
  withDangerousMod(config, [
    'android',
    cfg => {
      const appDir = path.join(cfg.modRequest.platformProjectRoot, 'app');
      const cppDir = path.join(appDir, 'src', 'main', 'cpp');
      fs.mkdirSync(cppDir, {recursive: true});
      fs.writeFileSync(path.join(appDir, 'CMakeLists.txt'), CMAKE_LISTS);
      fs.writeFileSync(path.join(cppDir, 'stub.cpp'), STUB_CPP);
      return cfg;
    },
  ]);

/**
 * Expo's template defaults android:allowBackup to true. The old manifest set it
 * to false deliberately: the app holds a signed-in Firebase session, and
 * Android's auto-backup would otherwise copy that state off the device.
 */
const withoutAutoBackup = config =>
  withAndroidManifest(config, cfg => {
    const application = cfg.modResults.manifest.application?.[0];
    if (application) {
      application.$['android:allowBackup'] = 'false';
    }
    return cfg;
  });

const withAllimNativeBuild = config =>
  withoutAutoBackup(withCMakeStubs(withAppGradle(withRootGradle(config))));

module.exports = createRunOncePlugin(
  withAllimNativeBuild,
  'withAllimNativeBuild',
  '1.0.0',
);
